"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, CheckCircle2, Eye, Heart, Loader2, MessageCircle, RotateCcw, Search, Send, Sparkles } from "lucide-react";
import { useGrio } from "@/components/grio/GrioProvider";
import { cn } from "@/lib/utils";
import { haptic } from "@/lib/motion";
import type { ReelCardViewModel, ReelPreferenceNotice, ReelRefineQuestion, ReelSwipeDirection } from "@/lib/contracts/reel";
import { REEL_LANES, type ReelLane, type ReelLaneCounts } from "@/lib/contracts/reelLibrary";
import { profileChips } from "./ReelProfileOverlay";
import { useT } from "@/components/i18n/LanguageProvider";

/**
 * Where the rishtey run out.
 *
 * Not an empty screen and not an advertisement — the two things this slot has
 * been before. It is one full-height card that closes the session, says what
 * actually happened in numbers that came from the member's own decisions, and
 * then offers to make what comes next better by asking for one thing at a time.
 *
 * ## It only appears when the pool is genuinely finished (D-91)
 *
 * This used to be the "aaj ke 15 khatam" card, shown every day at the number
 * the plan happened to carry. There is no such number now: `ReelStack` renders
 * this only after the server has said there is nobody left who matches and has
 * not already been seen. So the headline may say the one thing a member most
 * needs to be told honestly at this moment — that more will come later, and
 * that nothing is being held back from them in the meantime.
 *
 * ## Every sentence here is checkable
 *
 * The recap counts the decisions taken in this batch. The observations below
 * it are computed from those same decisions and are printed **only** when a
 * pattern genuinely repeats (`OBSERVATION_FLOOR`); with one shortlist and one
 * interest there is no pattern, so nothing is claimed. Nothing on this card is
 * generated by a model, and nothing extrapolates from behaviour into
 * personality.
 *
 * ## The refinement is a real save
 *
 * The questions are the profile catalog's own partner-preference questions,
 * already filtered on the server to the ones this member has left empty
 * (`refineQuestionsFor`). An answer goes through `/api/profile/save-draft` —
 * the same autosave the manual deck and the interview use — so what is stated
 * here is a preference like any other, and tomorrow's reel reads it without
 * anything being taught about this screen.
 *
 * What it does **not** do is claim the deck will re-deal itself. A preference
 * saved here shapes the *next* reel, not the cards already dealt and decided,
 * so there is no "aur dikhaiye" button on this card pretending otherwise —
 * that button lives one state earlier, where there genuinely is more to show.
 *
 * ## It ends with doors, not with a full stop
 *
 * For a long time the last thing on this card was a link home, and a member
 * who reached it was being told the app had nothing — while their Viewed lane
 * held sixty people whose cards they could still act on. D-91b built those
 * lanes and left them one tab away; this card now names them, with their real
 * counts, and only the ones that hold somebody. A lane with nobody in it is
 * not offered, because a row of zeroes is four more dead ends.
 */

/** How many of the member's own picks must agree before a pattern is named. */
const OBSERVATION_FLOOR = 2;

type Decisions = Record<string, ReelSwipeDirection>;

/** A pattern the member's picks actually repeat, or nothing. */
function observationsFor(
  cards: ReelCardViewModel[],
  decisions: Decisions,
  t: ReturnType<typeof useT>,
): string[] {
  // "Picked" is interest or shortlist — a LEFT is a decision too, but it says
  // far less: people skip for reasons they would not endorse as a preference.
  const picked = cards.filter((c) => decisions[c.id] === "RIGHT" || decisions[c.id] === "DOWN");
  if (picked.length < OBSERVATION_FLOOR) return [];

  const out: string[] = [];

  const cityCounts = new Map<string, number>();
  for (const c of picked) {
    if (!c.city) continue;
    const key = c.city.trim();
    cityCounts.set(key, (cityCounts.get(key) ?? 0) + 1);
  }
  const topCity = [...cityCounts.entries()].sort((a, b) => b[1] - a[1])[0];
  if (topCity && topCity[1] >= OBSERVATION_FLOOR) {
    out.push(
      t("reel.end.observationCity", "Aapki chuni hui profiles me se {n} {city} se thi.")
        .replace("{n}", String(topCity[1]))
        .replace("{city}", topCity[0]),
    );
  }

  // The same chips the cards showed, so a member can look back and see where
  // the observation came from instead of being told something about themselves.
  const traitCounts = new Map<string, number>();
  for (const c of picked) {
    for (const chip of profileChips(c, 4)) {
      if (chip.shared) continue; // pair overlap, not something about this person
      traitCounts.set(chip.text, (traitCounts.get(chip.text) ?? 0) + 1);
    }
  }
  const topTrait = [...traitCounts.entries()].sort((a, b) => b[1] - a[1])[0];
  if (topTrait && topTrait[1] >= OBSERVATION_FLOOR) {
    out.push(
      t("reel.end.observationTrait", "“{trait}” — ye baat aapki {n} pasand me common thi.")
        .replace("{trait}", topTrait[0])
        .replace("{n}", String(topTrait[1])),
    );
  }

  return out.slice(0, 2);
}

export default function ReelEndDiscovery({
  cards,
  decisions,
  seenCount,
  sentCount,
  shortlistCount,
  questions,
  preferenceNotice,
  laneCounts,
  onOpenLane,
  onSearch,
  onReplay,
}: {
  cards: ReelCardViewModel[];
  decisions: Decisions;
  /** Everything decided today, across reloads — not just this tab's swipes. */
  seenCount: number;
  sentCount: number;
  shortlistCount: number;
  questions: ReelRefineQuestion[];
  preferenceNotice: ReelPreferenceNotice | null;
  /** How many people sit in each history lane — a lane with nobody is not offered. */
  laneCounts: ReelLaneCounts;
  onOpenLane: (lane: ReelLane) => void;
  /** Opens the reel's own search sheet — the one thing a member can still do here and now. */
  onSearch: () => void;
  /** Present only when today's deck has cards to replay — absent on a genuinely empty pool. */
  onReplay?: () => void;
}) {
  const t = useT();
  const { open: openGrio } = useGrio();

  /**
   * The way out.
   *
   * This card used to end the reel with a search box and a link home, and for
   * a member whose pool had genuinely run dry that was the whole app saying
   * "nothing here". Their own history is the one piece of real inventory that
   * still exists at this moment — Viewed alone is usually the largest number
   * on the screen — and the reel's lanes are full decision surfaces, so
   * "dobara dekhein" is a true offer and not a consolation.
   *
   * Only lanes that actually hold somebody are offered: a row of four zeroes
   * would be four more dead ends.
   */
  const LANE_LABELS: Record<ReelLane, string> = {
    VIEWED: t("reel.tabs.viewed", "Viewed"),
    LIKED: t("reel.tabs.liked", "Liked"),
    INTEREST: t("reel.tabs.interest", "Interest"),
    MESSAGE: t("reel.tabs.message", "Messages"),
  };
  const LANE_ICONS: Record<ReelLane, typeof Eye> = {
    VIEWED: Eye,
    LIKED: Heart,
    INTEREST: Send,
    MESSAGE: MessageCircle,
  };
  const doors = REEL_LANES.filter((lane) => (laneCounts[lane] ?? 0) > 0);

  const [step, setStep] = useState(0);
  const [picked, setPicked] = useState<string[]>([]);
  const [saving, setSaving] = useState(false);
  const [savedCount, setSavedCount] = useState(0);
  const [failed, setFailed] = useState(false);

  const question = questions[step] ?? null;
  const observations = observationsFor(cards, decisions, t);

  async function save(value: string) {
    if (!question || saving) return;
    setSaving(true);
    setFailed(false);
    try {
      const res = await fetch("/api/profile/save-draft", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ values: { [question.key]: value } }),
      });
      if (!res.ok) {
        setFailed(true);
        return;
      }
      setSavedCount((n) => n + 1);
      advance();
    } catch {
      setFailed(true);
    } finally {
      setSaving(false);
    }
  }

  function advance() {
    setPicked([]);
    setStep((s) => s + 1);
  }

  function toggle(option: string) {
    if (!question) return;
    haptic("select");
    if (!question.multi) {
      void save(option);
      return;
    }
    setPicked((p) => (p.includes(option) ? p.filter((o) => o !== option) : [...p, option]));
  }

  return (
    <div className="mx-auto flex w-full max-w-md flex-1 flex-col overflow-y-auto px-4 pb-4">
      <div className="my-auto rounded-[1.5rem] border border-gold-200/70 bg-surface px-5 py-6 shadow-lg dark:border-gold-700/40">
        <span className="relative grid size-14 place-items-center rounded-full bg-gradient-to-br from-gold-400 to-gold-600 text-primary-fg shadow-gold">
          <span aria-hidden className="absolute inset-0 rounded-full bg-gold-400/35 blur-xl" />
          <CheckCircle2 className="relative size-7" aria-hidden />
        </span>

        <h2 className="mt-4 font-[family-name:var(--font-display)] text-[1.375rem] font-bold leading-tight text-accent-text">
          {t("reel.end.title", "Aapke liye abhi itne hi rishtey the.")}
        </h2>

        {/* Counts, not adjectives. Every number here is a row that exists —
            and when there are none (the pool ran out on an earlier day, so
            today held nothing to decide), the line is dropped rather than
            printed as three zeroes. */}
        {seenCount > 0 && (
          <p className="mt-1.5 text-[0.875rem] leading-relaxed text-muted">
            {t("reel.end.recap", "{seen} profiles dekhi — {interest} ko interest bheja, {shortlist} shortlist ki.")
              .replace("{seen}", String(seenCount))
              .replace("{interest}", String(sentCount))
              .replace("{shortlist}", String(shortlistCount))}
          </p>
        )}

        {/* The one sentence this screen exists to say honestly. Nothing is
            being withheld — there is simply nobody new right now. */}
        <p className="mt-2 rounded-lg bg-bg-subtle px-3 py-2.5 text-[0.8125rem] leading-relaxed text-ink">
          {t(
            "reel.end.exhausted",
            "Ab aapke liye matching rishtey baad me milenge — nayi profiles judte hi yahin dikhengi.",
          )}
        </p>

        {observations.length > 0 && (
          <ul className="mt-3 space-y-1.5 rounded-lg bg-bg-subtle px-3 py-2.5">
            {observations.map((line) => (
              <li key={line} className="flex items-start gap-2 text-[0.8125rem] leading-snug text-ink">
                <Sparkles className="mt-0.5 size-3.5 shrink-0 text-gold-700" aria-hidden />
                <span className="min-w-0">{line}</span>
              </li>
            ))}
          </ul>
        )}

        {/* Their own list, as doors rather than a sentence — directly under the
            bad news, because it is the answer to it.

            Deliberately outside the question/answer block below: the
            refinement asks up to four things, and while it was asking, this
            card had no exit on it at all. A member who had just been told
            "itne hi rishtey the" could not reach the sixty people in their own
            Viewed lane without first answering questions about their
            preferences — which is the dead end this card exists to not be. */}
        {doors.length > 0 && (
          <div className="mt-4 rounded-lg bg-bg-subtle px-3 py-3">
            <p className="text-[0.6875rem] font-semibold uppercase tracking-wider text-subtle">
              {t("reel.end.listLabel", "Aapki list")}
            </p>
            <p className="mt-1.5 text-[0.8125rem] leading-snug text-muted">
              {t(
                "reel.end.listBody",
                "Jinhe aap pehle dekh chuke hain — un par dobara nazar daal sakte hain, faisla wahin badal sakta hai.",
              )}
            </p>
            <div className="mt-2.5 flex flex-wrap gap-2">
              {doors.map((lane) => {
                const Icon = LANE_ICONS[lane];
                return (
                  <button
                    key={lane}
                    type="button"
                    onClick={() => {
                      haptic("tap");
                      onOpenLane(lane);
                    }}
                    className="inline-flex min-h-11 items-center gap-1.5 rounded-full border border-line-strong bg-surface px-3.5 text-[0.875rem] font-medium text-ink transition-colors hover:border-gold-400 hover:bg-gold-50 dark:hover:bg-gold-900/20"
                  >
                    <Icon className="size-4 shrink-0 text-gold-700" aria-hidden />
                    {LANE_LABELS[lane]}
                    <span className="tabular-nums text-[0.75rem] text-muted">{laneCounts[lane]}</span>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {/* ── One question at a time ─────────────────────────────────── */}
        {question ? (
          <div className="mt-5 border-t border-line pt-4">
            <p className="text-[0.6875rem] font-semibold uppercase tracking-wider text-subtle">
              {t("reel.end.refineLabel", "Aapke liye aur behtar rishte dhoondein?")}
            </p>
            {step === 0 && preferenceNotice && (
              <p className="mt-1.5 text-[0.75rem] leading-snug text-muted">{preferenceNotice.body}</p>
            )}

            <p className="mt-2 text-[0.9375rem] font-semibold leading-snug text-ink">{question.question}</p>

            <div className="mt-3 flex flex-wrap gap-2">
              {question.options.map((option) => {
                const on = picked.includes(option);
                return (
                  <button
                    key={option}
                    type="button"
                    disabled={saving}
                    onClick={() => toggle(option)}
                    aria-pressed={question.multi ? on : undefined}
                    className={cn(
                      "inline-flex min-h-11 items-center gap-1.5 rounded-full border px-3.5 text-[0.875rem] font-medium transition-colors disabled:opacity-50",
                      on
                        ? "border-gold-400 bg-gold-100 text-gold-700 dark:bg-gold-900/40 dark:text-gold-200"
                        : "border-line-strong bg-surface text-ink hover:border-gold-400 hover:bg-gold-50 dark:hover:bg-gold-900/20",
                    )}
                  >
                    {on && <Check className="size-3.5 shrink-0" aria-hidden />}
                    {option}
                  </button>
                );
              })}
            </div>

            {failed && (
              <p role="alert" className="mt-2 text-[0.75rem] text-danger">
                {t("reel.end.saveFailed", "Save nahi ho paaya — dobara try karein.")}
              </p>
            )}

            <div className="mt-3 flex items-center gap-2">
              {question.multi && (
                <button
                  type="button"
                  disabled={picked.length === 0 || saving}
                  onClick={() => save(picked.join(", "))}
                  className="inline-flex min-h-11 items-center gap-1.5 rounded-full bg-accent px-4 text-[0.875rem] font-semibold text-accent-fg transition-opacity disabled:opacity-40"
                >
                  {saving ? <Loader2 className="size-4 animate-spin" aria-hidden /> : null}
                  {t("reel.end.saveAnswer", "Save")}
                </button>
              )}
              <button
                type="button"
                disabled={saving}
                onClick={advance}
                className="min-h-11 rounded-full px-3 text-[0.875rem] font-medium text-muted transition-colors hover:bg-bg-subtle hover:text-ink"
              >
                {t("reel.end.skipQuestion", "Abhi nahi")}
              </button>
              <span className="ml-auto text-[0.75rem] tabular-nums text-subtle">
                {step + 1}/{questions.length}
              </span>
            </div>
          </div>
        ) : (
          <>
            {savedCount > 0 && (
              <p className="mt-4 flex items-start gap-2 rounded-lg bg-trust-bg px-3 py-2.5 text-[0.8125rem] leading-snug text-trust">
                <Check className="mt-0.5 size-4 shrink-0" aria-hidden />
                <span className="min-w-0">
                  {t("reel.end.saved", "Shukriya — {n} baat save ho gayi. Aage ke rishtey isi hisaab se aayenge.").replace(
                    "{n}",
                    String(savedCount),
                  )}
                </span>
              </p>
            )}

            {/* No "aur rishtey" button: the server has just said there are
                none, and a button that would come back empty is worse than no
                button. Search is offered instead because it asks a different
                question — one specific person, by name — that this pool being
                finished does not answer. */}
            <div className="mt-5 flex flex-col gap-2">
              <button
                type="button"
                onClick={() => {
                  haptic("tap");
                  onSearch();
                }}
                className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-accent px-5 text-[0.9375rem] font-semibold text-accent-fg"
              >
                <Search className="size-4" aria-hidden />
                {t("reel.end.openSearch", "Naam se dhoondein")}
                <ArrowRight className="size-4" aria-hidden />
              </button>

              <button
                type="button"
                onClick={() => {
                  haptic("tap");
                  openGrio();
                }}
                className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-wine-50 px-5 text-[0.9375rem] font-semibold text-wine-700 ring-1 ring-wine-200 transition-colors hover:bg-wine-100 dark:bg-wine-900/40 dark:text-wine-200 dark:ring-wine-700/50"
              >
                <Sparkles className="size-4" aria-hidden />
                {t("reel.end.talkToGrio", "Grio se baat karein")}
              </button>

              <div className="flex gap-2">
                {onReplay && (
                  <button
                    type="button"
                    onClick={onReplay}
                    className="inline-flex min-h-11 flex-1 items-center justify-center gap-1.5 rounded-full border border-line-strong px-3 text-[0.875rem] font-medium text-muted transition-colors hover:bg-bg-subtle hover:text-ink"
                  >
                    <RotateCcw className="size-4" aria-hidden />
                    {t("reel.emptyState.viewAgain", "View Again")}
                  </button>
                )}
                <Link
                  href="/user/dashboard"
                  className="inline-flex min-h-11 flex-1 items-center justify-center rounded-full border border-line-strong px-3 text-[0.875rem] font-medium text-muted transition-colors hover:bg-bg-subtle hover:text-ink"
                >
                  {t("reel.end.backHome", "Back Home")}
                </Link>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
