import type { MarketingPlan } from "../../lib/contracts/marketingPlanSchema";

/**
 * The one plan every marketing check reasons about — a full MKT-1 package
 * (Google Search + Meta + creative + landing) as the guardrails would have
 * saved it. Shared by `marketing-ai-check.ts` (pure pins) and
 * `marketing-execution-check.ts` (MKT-2, fake provider against the DB).
 */
export function fixturePlan(opts: { dailyRupees?: number } = {}): MarketingPlan {
  const daily = opts.dailyRupees ?? 500;
  return {
    clarifyingQuestion: null,
    diagnosis: "Jaipur me ladkiyon ki live profiles kam hain. Funnel register se live tak 40% par tootta hai. Search demand hai.",
    evidence: [
      { claim: "Register → live 40%", source: "bandhantak.growth", window: "last 30 days", geography: "all", value: "40%" },
      { claim: "'jaipur matrimony' 1,900 avg monthly searches", source: "google.keyword_ideas", window: "12-month average", geography: "Jaipur", value: "1,900" },
    ],
    assumptions: ["CPC estimate ₹8-14 (Keyword Planner top-of-page bids)"],
    missingData: ["Meta Ads not connected"],
    goal: {
      name: "Jaipur verified women profiles — 30 din",
      objective: "VERIFIED_PROFILE",
      geography: "Jaipur",
      audienceSide: "women",
      windowDays: 30,
      primaryConversion: "verification_completed",
      baseline: { metric: "verification_completed", value: 12, window: "last 30 days", source: "bandhantak.growth" },
      targetFromAdmin: null,
      dailyBudgetRupees: null,
      totalBudgetRupees: null,
      channels: ["GOOGLE_SEARCH", "INSTAGRAM_REELS"],
      constraints: ["Hinglish copy"],
      stopLossRule: "₹1,500 spend ke baad zero completed profile ho to pause proposal",
    },
    recommendedPlan: {
      goalSummary: "Jaipur me 30 din me verified women profiles badhana",
      targetAudience: "Jaipur ki 22-30 saal ki working women aur unke parents",
      offer: "Verified rishte, family ke saath, free kundli",
      channelChoices: [
        { channel: "GOOGLE_SEARCH", reason: "High-intent demand", budgetSharePct: 60 },
        { channel: "INSTAGRAM_REELS", reason: "Trust proof visually", budgetSharePct: 40 },
      ],
      testingPlan: ["2 ad groups vs each other"],
      successConditions: ["Cost per verified profile < ₹400"],
      failureConditions: ["Zero verified after ₹1,500"],
      budget: { dailyRupees: daily, totalRupees: daily * 30, windowDays: 30 },
    },
    topics: [
      {
        topic: "Verified profiles ki zaroorat",
        whyThisTopic: "Search Console me 'verified matrimony' rising",
        source: "google.search_console",
        geography: "India",
        window: "last 28 days vs previous",
        bandhantakAngle: "Photo/contact verification",
        audience: "women 22-30",
        conversionGoal: "verification_completed",
        scores: { demandEvidence: 4, relevance: 5, audienceFit: 4, productTruth: 5, creativePotential: 4, safety: 5 },
        rejected: false,
        rejectionReason: null,
      },
    ],
    googleSearch: {
      campaignName: "BT · Jaipur · Verified Women · Search",
      locations: ["Jaipur, Rajasthan, India"],
      language: "Hindi, English",
      network: "SEARCH",
      adGroups: [
        {
          name: "Jaipur matrimony",
          theme: "city intent",
          keywords: [
            { text: "jaipur matrimony", matchType: "PHRASE" },
            { text: "matrimony in jaipur", matchType: "EXACT" },
          ],
          headlines: ["Jaipur Verified Matrimony", "Family Ke Saath Rishta", "Free Kundli Milan"],
          descriptions: ["Verified profiles, family controls aur roz limited curated rishte.", "Bol kar profile banaiye — 5 minute me."],
        },
      ],
      negativeKeywords: ["free", "dating", "job"],
      sitelinks: [{ text: "How it works", path: "/how-it-works" }],
      callouts: ["Verified profiles", "Family Circle"],
      landingPath: "/register",
      utm: { source: "google", medium: "cpc", campaign: "jaipur-verified-women-2026-09", content: "{creative}" },
      dailyBudgetRupees: Math.round(daily * 0.6),
      biddingStrategy: "MAXIMIZE_CONVERSIONS",
      targetCpaRupees: null,
      conversionAction: "verification_completed",
      rationale: "High-intent search demand in Jaipur.",
    },
    meta: {
      campaignName: "BT · Jaipur · Reels",
      objective: "OUTCOME_LEADS",
      audience: {
        description: "Jaipur ki 22-30 saal ki women aur unke parents.",
        ageMin: 22,
        ageMax: 45,
        genders: ["women"],
        locations: ["Jaipur"],
        interests: ["Wedding planning"],
        exclusions: [],
      },
      adSets: [{ name: "Reels · women 22-30", audienceNote: "core", placements: ["instagram_reels"], dailyBudgetRupees: Math.round(daily * 0.4), creativeIds: ["reel-1", "reel-2"] }],
      ads: [
        { id: "ad-1", name: "Reel 1", format: "REEL", primaryText: "Verified profiles, family ke saath.", headline: "Jaipur Verified Rishte", description: "Bol kar profile banaiye", cta: "SIGN_UP", creativeId: "reel-1" },
      ],
      landingPath: "/register",
      utm: { source: "instagram", medium: "paid_social", campaign: "jaipur-verified-women-2026-09", content: "{creative}" },
      schedule: { startDate: "2026-09-15", endDate: "2026-10-15" },
      frequencyCap: "2 impressions / 7 days",
      stopLoss: "₹1,500 spend, zero registrations → pause proposal",
      dailyBudgetRupees: Math.round(daily * 0.4),
      rationale: "Trust proof works visually.",
    },
    creative: {
      hooks: [
        { id: "hook-1", text: "Profile banana mushkil lagta hai?", angle: "PROBLEM_RELIEF" },
        { id: "hook-2", text: "Verified matlab kya?", angle: "TRUST_PROOF" },
        { id: "hook-3", text: "Roz 5 rishte, sirf aapke liye", angle: "PRODUCT_DEMO" },
      ],
      visualDirections: ["Real app screens", "Family at dining table", "Kinetic text"],
      videos: [
        {
          id: "reel-1",
          format: "REEL",
          concept: "PROBLEM_RELIEF",
          hookId: "hook-1",
          title: "Bol kar profile",
          hook: "Profile banana mushkil lagta hai?",
          script: "Grio se baat kijiye aur profile ban jaati hai.",
          storyboard: ["Phone screen, Grio bubble"],
          onScreenText: ["Bol kar profile"],
          voiceover: "Bol kar profile banaiye.",
          subtitleText: "Bol kar profile banaiye.",
          musicMood: "warm, hopeful",
          coverText: "Bol kar profile",
          caption: "Grio se profile banaiye.",
          cta: "Register karein",
          durationSec: 30,
          utmContent: "reel-1",
          complianceNotes: ["No user photos"],
        },
        {
          id: "reel-2",
          format: "REEL",
          concept: "TRUST_PROOF",
          hookId: "hook-2",
          title: "Verified matlab",
          hook: "Verified matlab kya?",
          script: "Photo aur contact verification, family controls.",
          storyboard: ["Badge close-up"],
          onScreenText: ["Verified"],
          voiceover: "Verified profiles.",
          subtitleText: "Verified profiles.",
          musicMood: "calm",
          coverText: "Verified",
          caption: "Verified profiles.",
          cta: "Register karein",
          durationSec: 15,
          utmContent: "reel-2",
          complianceNotes: [],
        },
      ],
      statics: [{ id: "static-1", hookId: "hook-3", headline: "Roz 5 rishte", subline: "Sirf aapke liye chune hue", visualDirection: "App screen", cta: "Register karein" }],
      brandSafetyChecklist: ["No guarantees", "No urgency"],
    },
    landing: {
      useExistingPage: true,
      path: "/register",
      heroHeadline: "Verified rishte, family ke saath",
      subCopy: "Bol kar profile banaiye.",
      primaryCta: "Register karein",
      trustProof: ["Photo verification"],
      verificationExplainer: "Photo aur contact verify hote hain.",
      grioVoiceCta: true,
      analyticsEvents: ["registration_started", "verification_completed"],
      changesNeeded: [],
    },
    requestedToolCalls: [{ tool: "google.campaign.create_paused", reason: "After approval" }],
    approvalsNeeded: [{ action: "CREATE_PAUSED_CAMPAIGNS", what: "Google + Meta paused", budgetRupees: daily }],
    successMetric: "Cost per verified profile",
    stopConditions: ["₹1,500 spend, zero verified"],
    nextReviewAt: "2026-09-19",
  };
}
