import "server-only";
import { mkdir, readFile, unlink, writeFile } from "fs/promises";
import path from "path";
import { randomUUID } from "crypto";
import type { MediaKind } from "@prisma/client";

/**
 * Storage for gated files — voice notes today, blurred photo derivatives later.
 *
 * ## Why this is not `photoStorage`
 *
 * `photoStorage` writes into `public/uploads/**`, which Next serves statically
 * with no auth at all. That is fine for a photo whose whole purpose is to be
 * seen once a match exists — and it is exactly why `reelData.ts` withholds the
 * *URL* for locked profiles rather than blurring the image.
 *
 * A voice note has no such "eventually public" state. A locked note must stay
 * unreadable even to someone who guesses the filename, so nothing here may
 * ever land under `public/`. `MEDIA_ROOT` sits beside it, outside the served
 * tree, and the only way bytes leave this module is `GET /api/media/[id]`,
 * which re-checks permission per request.
 *
 * ## The R2 seam
 *
 * Same shape as `PhotoStorage`: swapping to Cloudflare R2 (D-30) means writing
 * one class that implements `MediaStorage` and changing the export at the
 * bottom. `read()` returning a Buffer rather than a stream is a deliberate
 * simplification — a 10-second Opus clip is ~15KB, and streaming machinery for
 * that would be cost with no benefit. Revisit if video ever lands.
 */

export interface StoredMedia {
  storageKey: string;
  sizeBytes: number;
}

export interface MediaStorage {
  upload(params: {
    userId: string;
    kind: MediaKind;
    buffer: Buffer;
    extension: string;
  }): Promise<StoredMedia>;
  read(storageKey: string): Promise<Buffer>;
  remove(storageKey: string): Promise<void>;
}

const MEDIA_ROOT = path.join(process.cwd(), "private-media");

const KIND_DIR: Record<MediaKind, string> = {
  VOICE_NOTE: "voice",
  PHOTO_BLUR_DERIVATIVE: "blur",
};

/**
 * Rejects any key that could escape MEDIA_ROOT. Keys are generated by this
 * module and stored in our own DB, so a traversal attempt means something is
 * already wrong — but the check costs nothing and the failure mode it prevents
 * is "read any file on the server".
 */
function resolveKey(storageKey: string): string {
  const full = path.resolve(MEDIA_ROOT, storageKey);
  const root = path.resolve(MEDIA_ROOT);
  if (full !== root && !full.startsWith(root + path.sep)) {
    throw new Error("Invalid storage key.");
  }
  return full;
}

class LocalDiskMediaStorage implements MediaStorage {
  async upload({
    userId,
    kind,
    buffer,
    extension,
  }: {
    userId: string;
    kind: MediaKind;
    buffer: Buffer;
    extension: string;
  }): Promise<StoredMedia> {
    const storageKey = `${KIND_DIR[kind]}/${userId}/${randomUUID()}.${extension}`;
    const filePath = resolveKey(storageKey);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, buffer);
    return { storageKey, sizeBytes: buffer.byteLength };
  }

  async read(storageKey: string): Promise<Buffer> {
    return readFile(resolveKey(storageKey));
  }

  async remove(storageKey: string): Promise<void> {
    await unlink(resolveKey(storageKey)).catch(() => {});
  }
}

export const mediaStorage: MediaStorage = new LocalDiskMediaStorage();
