import "server-only";
import { mkdir, readFile, unlink, writeFile } from "fs/promises";
import path from "path";
import { randomUUID } from "crypto";
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand } from "@aws-sdk/client-s3";
import type { MediaKind } from "@prisma/client";
import { isObjectStoreConfigured, objectBucket, objectClient } from "./objectStore";

/**
 * Storage for gated files — voice notes today, blurred photo derivatives later.
 *
 * ## Why this is not `photoStorage`
 *
 * `photoStorage` writes into `public/uploads/**`, which Next serves statically
 * with no auth at all. That is fine for a photo whose whole purpose is to be
 * seen once a match exists — and it is exactly why `reelData.ts` withholds the
 * *URL* for locked profiles rather than blurring the image.
 *
 * A voice note has no such "eventually public" state. A locked note must stay
 * unreadable even to someone who guesses the filename, so nothing here may
 * ever land under `public/`. `MEDIA_ROOT` sits beside it, outside the served
 * tree, and the only way bytes leave this module is `GET /api/media/[id]`,
 * which re-checks permission per request.
 *
 * ## The object-store backend
 *
 * `S3MediaStorage` below is that swap, taken. It is chosen at module load when
 * a bucket is configured and falls back to disk otherwise, so a developer
 * checkout still works with no cloud account.
 *
 * The privacy argument survives the move intact, and for a better reason than
 * before: objects go under a `media/` prefix in the same bucket as photos, but
 * bytes still only leave through `GET /api/media/[id]`, which re-checks
 * permission per request. Nothing here ever returns a public URL — that is the
 * difference from `photoStorage`, and it is why this module has no `fileUrl`.
 * **The bucket must not be world-readable at the `media/` prefix.**
 *
 * `read()` returning a Buffer rather than a stream is a deliberate
 * simplification — a 10-second Opus clip is ~15KB, and streaming machinery for
 * that would be cost with no benefit. Revisit if video ever lands.
 */

export interface StoredMedia {
  storageKey: string;
  sizeBytes: number;
}

export interface MediaStorage {
  upload(params: {
    userId: string;
    kind: MediaKind;
    buffer: Buffer;
    extension: string;
  }): Promise<StoredMedia>;
  read(storageKey: string): Promise<Buffer>;
  remove(storageKey: string): Promise<void>;
}

const MEDIA_ROOT = path.join(process.cwd(), "private-media");

const KIND_DIR: Record<MediaKind, string> = {
  VOICE_NOTE: "voice",
  PHOTO_BLUR_DERIVATIVE: "blur",
};

/**
 * Rejects any key that could escape MEDIA_ROOT. Keys are generated by this
 * module and stored in our own DB, so a traversal attempt means something is
 * already wrong — but the check costs nothing and the failure mode it prevents
 * is "read any file on the server".
 */
function resolveKey(storageKey: string): string {
  const full = path.resolve(MEDIA_ROOT, storageKey);
  const root = path.resolve(MEDIA_ROOT);
  if (full !== root && !full.startsWith(root + path.sep)) {
    throw new Error("Invalid storage key.");
  }
  return full;
}

class LocalDiskMediaStorage implements MediaStorage {
  async upload({
    userId,
    kind,
    buffer,
    extension,
  }: {
    userId: string;
    kind: MediaKind;
    buffer: Buffer;
    extension: string;
  }): Promise<StoredMedia> {
    const storageKey = `${KIND_DIR[kind]}/${userId}/${randomUUID()}.${extension}`;
    const filePath = resolveKey(storageKey);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, buffer);
    return { storageKey, sizeBytes: buffer.byteLength };
  }

  async read(storageKey: string): Promise<Buffer> {
    return readFile(resolveKey(storageKey));
  }

  async remove(storageKey: string): Promise<void> {
    await unlink(resolveKey(storageKey)).catch(() => {});
  }
}

/** Keeps gated media in its own prefix, away from the public `photos/` one. */
const MEDIA_PREFIX = "media";

class S3MediaStorage implements MediaStorage {
  async upload({
    userId,
    kind,
    buffer,
    extension,
  }: {
    userId: string;
    kind: MediaKind;
    buffer: Buffer;
    extension: string;
  }): Promise<StoredMedia> {
    const storageKey = `${KIND_DIR[kind]}/${userId}/${randomUUID()}.${extension}`;
    await objectClient().send(
      new PutObjectCommand({
        Bucket: objectBucket,
        Key: `${MEDIA_PREFIX}/${storageKey}`,
        Body: buffer,
        // No CacheControl and no public URL: every read goes back through
        // /api/media/[id] so the permission check cannot be cached past a
        // change in who is allowed to hear it.
        CacheControl: "private, no-store",
      }),
    );
    return { storageKey, sizeBytes: buffer.byteLength };
  }

  async read(storageKey: string): Promise<Buffer> {
    const res = await objectClient().send(
      new GetObjectCommand({ Bucket: objectBucket, Key: `${MEDIA_PREFIX}/${storageKey}` }),
    );
    if (!res.Body) throw new Error("Media object has no body.");
    return Buffer.from(await res.Body.transformToByteArray());
  }

  async remove(storageKey: string): Promise<void> {
    await objectClient()
      .send(new DeleteObjectCommand({ Bucket: objectBucket, Key: `${MEDIA_PREFIX}/${storageKey}` }))
      .catch(() => {});
  }
}

export const mediaStorage: MediaStorage = isObjectStoreConfigured()
  ? new S3MediaStorage()
  : new LocalDiskMediaStorage();
