export const ROUTES = {
  public: {
    home: "/",
    howItWorks: "/how-it-works",
    pricing: "/pricing",
    partnerProgram: "/partner-program",
    safety: "/safety",
    login: "/login",
    register: "/register",
  },
  user: {
    dashboard: "/user/dashboard",
    profileSetup: "/user/profile-setup",
    profileTrustScore: "/user/profile-trust-score",
    matches: "/user/matches",
    interests: "/user/interests",
    messages: "/user/messages",
    subscription: "/user/subscription",
  },
  partner: {
    register: "/partner/register",
    pending: "/partner/pending",
    dashboard: "/partner/dashboard",
    leads: "/partner/leads",
    referralTools: "/partner/referral-tools",
    commissions: "/partner/commissions",
    payouts: "/partner/payouts",
  },
  admin: {
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    profiles: "/admin/profiles",
    partners: "/admin/partners",
    referrals: "/admin/referrals",
    commissions: "/admin/commissions",
    payouts: "/admin/payouts",
    auditLogs: "/admin/audit-logs",
    verification: "/admin/verification",
  },
} as const;