/**
 * Snapshot of the web app's profile + search catalog for the native app, and
 * the web's pure profile rules copied in beside it.
 *
 * The web keeps one source of truth for what a profile asks and how it is
 * answered — `lib/profile/fields.ts` (the fields), `fieldGroups.ts` (how a
 * person groups them), `quickPicks.ts` (the tap-first answers) and
 * `lib/discovery/contract.ts` (the search filters). The app renders the same
 * catalog instead of keeping a second copy by hand: this script serialises it
 * to `src/catalog/catalog.generated.json`, which the app bundles.
 *
 * The rules that *judge* answers are code, not data, so they are copied as
 * code (`VENDORED` below): readiness (what counts as a valid value, the eight
 * a live profile needs), the password policy, and the whole of `/bolo`'s pure
 * logic — the draft's normalisation and `acceptAnswers`, the question ladder
 * and its chips, Grio's brief, the mic gate. Each copy is the web file with
 * only its import paths rewritten, so the app and the server accept exactly
 * the same answers. Nothing is edited by hand on this side.
 *
 * Grio's contract travels the same way: the action catalog, its markers and
 * their parser, and the concierge response shapes (`src/shared/grio/`), plus
 * the Marriage Intelligence questions a `<<<LEARN:>>>` card asks
 * (`src/catalog/grio.generated.json`). The app is a surface over the web's
 * Grio brain; its buttons and their wording are the web catalog's.
 *
 * Run from the repository root after any catalog or rule change:
 *
 *   npx tsx mobile/scripts/sync-catalog.ts          # write the snapshot + copies
 *   npx tsx mobile/scripts/sync-catalog.ts --check  # exit 1 if any is stale
 *
 * The server stays the authority either way — `/api/profile/save-draft` and
 * `/api/bolo/complete` re-validate every value against the live catalog — so a
 * stale copy can at worst offer an outdated option, never store an invalid one.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { PROFILE_FIELDS } from "../../lib/profile/fields";
import { FIELD_CATEGORIES, fieldsInCategory } from "../../lib/profile/fieldGroups";
import {
  COMPOSE_CARDS,
  COMMUNITY_BY_RELIGION,
  INDIA_PLACES,
  POPULAR_CITIES,
  QUICK_PICKS,
  SAME_AS_PREFIX,
} from "../../lib/profile/quickPicks";
import {
  DISCOVER_MAX_AGE,
  DISCOVER_MAX_HEIGHT_CM,
  DISCOVER_MIN_AGE,
  DISCOVER_MIN_HEIGHT_CM,
  DISCOVER_PAGE_SIZE,
  FILTER_CATALOG,
  FILTER_GROUP_LABELS,
  SENSITIVE_CONSENT_LABELS,
} from "../../lib/discovery/contract";
import {
  FEED_PREFERENCE_FIELDS,
  FEED_QUESTION_EVERY,
  FEED_QUESTION_FIELDS,
  FEED_QUESTION_FIRST_AFTER,
  FEED_QUESTION_MAX_OPTIONS,
  FEED_QUESTION_MAX_PER_VISIT,
  NEVER_A_FEED_QUESTION,
} from "../../lib/reel/feedQuestions";
import { REPORT_REASONS } from "../../lib/constants/reportReasons";
import { DEAL_BREAKER_LABEL, INTELLIGENCE_QUESTIONS } from "../../lib/profile/intelligenceQuestions";
import { QUESTION_MAX_LENGTH } from "../../lib/contracts/askBridge";

const OUT = path.join(__dirname, "..", "src", "catalog", "catalog.generated.json");
const GRIO_OUT = path.join(__dirname, "..", "src", "catalog", "grio.generated.json");

const snapshot = {
  $comment: "GENERATED by mobile/scripts/sync-catalog.ts from the web catalog. Do not edit by hand.",
  fields: PROFILE_FIELDS.map((f) => ({
    key: f.key,
    label: f.label,
    stage: f.stage,
    type: f.type,
    options: f.options ?? null,
    required: f.required,
    placeholder: f.placeholder ?? null,
    question: f.question,
    questionForChild: f.questionForChild,
    whyNeeded: f.whyNeeded ?? null,
    aiExtractable: f.aiExtractable,
    sensitive: f.sensitive ?? false,
    suggestions: f.suggestions ?? null,
  })),
  categories: FIELD_CATEGORIES.map((c) => ({
    key: c.key,
    label: c.label,
    hint: c.hint,
    fields: fieldsInCategory(c.key).map((f) => f.key),
  })),
  quickPicks: QUICK_PICKS,
  sameAsPrefix: SAME_AS_PREFIX,
  composeCards: COMPOSE_CARDS,
  places: INDIA_PLACES,
  popularCities: POPULAR_CITIES,
  communityByReligion: COMMUNITY_BY_RELIGION,
  // "Reel dekhte-dekhte profile" — which of the member's own fields the feed
  // may ask, and how far apart (the server picks the questions; the pacing is
  // the client's, the same numbers the web reel uses).
  feedQuestions: {
    fields: FEED_QUESTION_FIELDS,
    preferenceFields: FEED_PREFERENCE_FIELDS,
    never: NEVER_A_FEED_QUESTION,
    firstAfter: FEED_QUESTION_FIRST_AFTER,
    every: FEED_QUESTION_EVERY,
    maxPerVisit: FEED_QUESTION_MAX_PER_VISIT,
    maxOptions: FEED_QUESTION_MAX_OPTIONS,
  },
  // The safety sheet's reasons — also the admin queue's filter vocabulary.
  reportReasons: REPORT_REASONS,
  discover: {
    pageSize: DISCOVER_PAGE_SIZE,
    minAge: DISCOVER_MIN_AGE,
    maxAge: DISCOVER_MAX_AGE,
    minHeightCm: DISCOVER_MIN_HEIGHT_CM,
    maxHeightCm: DISCOVER_MAX_HEIGHT_CM,
    filters: FILTER_CATALOG,
    groupLabels: FILTER_GROUP_LABELS,
    sensitiveConsentLabels: SENSITIVE_CONSENT_LABELS,
  },
};

const json = `${JSON.stringify(snapshot, null, 2)}\n`;

/**
 * Grio's reference data the app renders but must not restate: the Marriage
 * Intelligence questions a `<<<LEARN:key=option>>>` card asks (the catalog's own
 * wording and options — the server rejects anything else), and the Ask Bridge
 * ceiling the question editor enforces. Only the fields the card reads.
 */
const grioSnapshot = {
  $comment: "GENERATED by mobile/scripts/sync-catalog.ts from the web catalog. Do not edit by hand.",
  askQuestionMaxLength: QUESTION_MAX_LENGTH,
  learnQuestions: INTELLIGENCE_QUESTIONS.map((q) => ({
    key: q.key,
    label: q.label,
    question: q.question,
    options: q.options,
    multi: q.multi ?? false,
    visibility: q.visibility,
  })),
  dealBreakerLabel: DEAL_BREAKER_LABEL,
};

const grioJson = `${JSON.stringify(grioSnapshot, null, 2)}\n`;

/* ------------------------------------------------------------------ */
/* The web's pure rules, copied as code                                */
/* ------------------------------------------------------------------ */

const REPO = path.join(__dirname, "..", "..");

/** Web file → where the app keeps its copy. Relative imports between two copied files stay as written. */
const VENDORED: Array<{ from: string; to: string }> = [
  { from: "lib/profile/readiness.ts", to: "mobile/src/shared/readiness.ts" },
  { from: "lib/auth/passwordPolicy.ts", to: "mobile/src/shared/passwordPolicy.ts" },
  { from: "lib/bolo/draft.ts", to: "mobile/src/shared/bolo/draft.ts" },
  { from: "lib/bolo/questions.ts", to: "mobile/src/shared/bolo/questions.ts" },
  { from: "lib/bolo/agent.ts", to: "mobile/src/shared/bolo/agent.ts" },
  { from: "lib/bolo/micGate.ts", to: "mobile/src/shared/bolo/micGate.ts" },
  // The admin's glass knobs → the pane (body ladder, shipped glass, ranges):
  // the numbers the app turns into native material must be the web's own.
  { from: "lib/theme/contrast.ts", to: "mobile/src/shared/theme/contrast.ts" },
  { from: "lib/theme/glass.ts", to: "mobile/src/shared/theme/glass.ts" },
  // Grio's contract: the action catalog (`GRIO_ACTIONS` — keys, labels, the
  // endpoint each row posts to), its markers and their parser, and the shapes
  // the concierge routes answer with. The app drives the web's Grio brain, so
  // it reads the same catalog instead of keeping a second list of buttons.
  { from: "lib/contracts/grio.ts", to: "mobile/src/shared/grio/grio.ts" },
  { from: "lib/contracts/concierge.ts", to: "mobile/src/shared/grio/concierge.ts" },
  { from: "lib/contracts/grioProfile.ts", to: "mobile/src/shared/grio/grioProfile.ts" },
  { from: "lib/contracts/grioCards.ts", to: "mobile/src/shared/grio/grioCards.ts" },
];

/**
 * Every import a copied file may make, and where it points in the app. A web
 * file that starts importing anything else fails the sync loudly — a copy that
 * silently reached back into the server would not bundle, or worse, would.
 */
const IMPORT_MAP: Record<string, Record<string, string>> = {
  "lib/profile/readiness.ts": { "./fields": "~/catalog/fields", "./stages": "~/catalog/fields" },
  "lib/auth/passwordPolicy.ts": {},
  "lib/bolo/draft.ts": {
    "@/lib/profile/fields": "~/catalog/fields",
    "@/lib/profile/readiness": "~/shared/readiness",
    "@/lib/contracts/interview": "~/types/api",
  },
  "lib/bolo/questions.ts": {
    "@/lib/contracts/interview": "~/types/api",
    "@/lib/profile/fields": "~/catalog/fields",
    "@/lib/profile/readiness": "~/shared/readiness",
    "./draft": "./draft",
  },
  "lib/bolo/agent.ts": {
    "@/lib/contracts/interview": "~/types/api",
    "@/lib/profile/fields": "~/catalog/fields",
    "@/lib/profile/readiness": "~/shared/readiness",
    "./draft": "./draft",
    "./questions": "./questions",
  },
  "lib/bolo/micGate.ts": {},
  "lib/theme/contrast.ts": {},
  "lib/theme/glass.ts": { "@/lib/theme/contrast": "./contrast" },
  "lib/contracts/grio.ts": { "./concierge": "./concierge" },
  "lib/contracts/concierge.ts": { "@/lib/contracts/grioProfile": "./grioProfile" },
  // `PhotoLock` is one string union the app already declares beside the other
  // API shapes; the web module it lives in also carries a translator the app
  // has no use for.
  "lib/contracts/grioProfile.ts": { "@/lib/contracts/photoLock": "~/types/api", "@/lib/contracts/grio": "./grio" },
  "lib/contracts/grioCards.ts": { "@/lib/contracts/photoLock": "~/types/api" },
};

/**
 * Two web modules the app keeps in one place (`./fields` and `./stages` are
 * both `~/catalog/fields`) would leave two imports of the same module behind.
 * Single-line named imports of one module are folded into the first of them
 * (`import type { X }` becoming `type X`), so a copy reads as if it were
 * written here.
 */
function foldDuplicateImports(code: string): string {
  const NAMED = /^import (type )?\{ ([^}]+) \} from "([^"]+)";$/;
  const lines = code.split("\n");
  const first = new Map<string, number>();
  const names = new Map<string, string[]>();
  const drop = new Set<number>();
  lines.forEach((line, i) => {
    const m = NAMED.exec(line);
    if (!m) return;
    const [, typeOnly, list, spec] = m;
    const parts = list!.split(",").map((n) => n.trim()).filter(Boolean).map((n) => (typeOnly && !n.startsWith("type ") ? `type ${n}` : n));
    if (first.has(spec!)) drop.add(i);
    else first.set(spec!, i);
    names.set(spec!, [...(names.get(spec!) ?? []), ...parts]);
  });
  if (drop.size === 0) return code;
  for (const [spec, i] of first) {
    const all = [...new Set(names.get(spec)!)];
    const allTypes = all.every((n) => n.startsWith("type "));
    lines[i] = allTypes
      ? `import type { ${all.map((n) => n.slice(5)).join(", ")} } from "${spec}";`
      : `import { ${all.join(", ")} } from "${spec}";`;
  }
  return lines.filter((_, i) => !drop.has(i)).join("\n");
}

function vendor(from: string): string {
  const source = readFileSync(path.join(REPO, from), "utf8").replace(/\r\n/g, "\n");
  const allowed = IMPORT_MAP[from] ?? {};
  const body = foldDuplicateImports(
    source
      .replace(/^"use client";\n+/, "")
      // Import and re-export statements only — a line that *starts* one, or the
      // `} from "…"` closing a multi-line one. Prose in a comment ("proposed
      // from "one message to one match"") is not an import.
      .replace(/^((?:import|export)\b[^\n]*?\bfrom\s+|\}\s*from\s+|import\s+)(["'])([^"']+)\2/gm, (whole, lead: string, quote: string, spec: string) => {
        const target = allowed[spec];
        if (!target) throw new Error(`${from} imports "${spec}", which the app has no copy of — add it to IMPORT_MAP.`);
        return `${lead}${quote}${target}${quote}`;
      }),
  );
  return (
    `// GENERATED from ${from} by mobile/scripts/sync-catalog.ts — do not edit.\n` +
    `// The web file is the one source of truth: change it there, then run\n` +
    `// \`npm run sync-catalog\` in mobile/. \`npm run check-catalog\` fails on drift.\n\n` +
    body
  );
}

const outputs: Array<{ file: string; content: string }> = [
  { file: OUT, content: json },
  { file: GRIO_OUT, content: grioJson },
  ...VENDORED.map(({ from, to }) => ({ file: path.join(REPO, to), content: vendor(from) })),
];

if (process.argv.includes("--check")) {
  const stale = outputs.filter(({ file, content }) => {
    try {
      return readFileSync(file, "utf8").replace(/\r\n/g, "\n") !== content;
    } catch {
      return true; // Missing counts as stale.
    }
  });
  if (stale.length > 0) {
    for (const { file } of stale) console.error(`stale: ${path.relative(process.cwd(), file)}`);
    console.error("Run: npx tsx mobile/scripts/sync-catalog.ts");
    process.exit(1);
  }
  console.log(`catalog.generated.json, grio.generated.json and ${VENDORED.length} shared rule files are up to date.`);
} else {
  for (const { file, content } of outputs) {
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, content);
  }
  console.log(
    `Wrote ${path.relative(process.cwd(), OUT)} — ${snapshot.fields.length} fields, ` +
      `${snapshot.discover.filters.length} filters, ${snapshot.places.length} states — ` +
      `${path.relative(process.cwd(), GRIO_OUT)} — ${grioSnapshot.learnQuestions.length} learn questions — ` +
      `and ${VENDORED.length} shared rule files.`,
  );
}
