import "server-only";
import type { Prisma, SpotlightCampaign } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { createNotice } from "@/lib/services/notice/noticeService";
import { loadAdvertiserFacts, type AdvertiserFacts } from "./eligibility";
import { audienceWhere, resolveExclusions } from "./audience";
import {
  MAX_PROMOTED_PER_REEL,
  MAX_PROMOTED_PER_VIEWER_PER_DAY,
  MIN_ORGANIC_CARDS_BEFORE_PROMOTED,
} from "./spotlightPolicy";

/**
 * Spotlight, delivered.
 *
 * Phase One sold campaigns, targeted them, estimated their audience and drew a
 * progress bar. It never put a single card in front of anybody:
 * `deliveredReach` had no writer, so every campaign ever bought read `0 / 50`
 * forever. This file is the half that was missing.
 *
 * ## Two events, not one
 *
 * A promoted card has two moments in its life and they are deliberately not
 * the same moment:
 *
 *   **Placement** — `placeSpotlightCard` picks a campaign while the viewer's
 *   reel is being generated, and the chosen campaign's id is written on the
 *   `DailyReelProfile` row. Nothing is charged against the promise.
 *
 *   **Delivery** — `recordReelDeliveries` runs when the viewer actually
 *   *opens* that reel, writes the `SpotlightDelivery` row and moves
 *   `deliveredReach`.
 *
 * They are split because a reel is generated by things that are not a person
 * looking at it: the dashboard builds one, Grio's roster builds one, the
 * concierge walkthrough builds one. If placement counted as reach, a buyer
 * would be charged for fifty decks that fifty people never opened, and the
 * number on their progress bar would be one nobody could verify from their own
 * use of the product. A card in an unopened deck reached nobody. The two
 * timestamps are both kept, so the gap between them is measurable rather than
 * assumed away.
 *
 * ## What the selector is not allowed to do
 *
 * Everything Phase One's policy file promised is enforced here and nowhere
 * else: never in the first `MIN_ORGANIC_CARDS_BEFORE_PROMOTED` cards, at most
 * `MAX_PROMOTED_PER_REEL` in a deck, at most
 * `MAX_PROMOTED_PER_VIEWER_PER_DAY` for one member across every surface, and
 * — the one that matters most — the viewer has to be somebody the campaign was
 * *already* allowed to reach. That last check reuses `audienceWhere`, the same
 * function the estimator quoted the buyer off, rather than a second query that
 * agrees with it today and drifts from it in six months.
 *
 * So paying moves a profile into a deck it could have organically appeared in.
 * It cannot put anyone in front of a person whose stated preferences exclude
 * them, past a block, or past a swipe they already made.
 */

/** One live campaign, reduced to what the selector needs to choose between them. */
interface Contender {
  campaign: SpotlightCampaign;
  advertiser: AdvertiserFacts;
  remaining: number;
}

/**
 * Campaigns that are running right now and still owe somebody reach.
 *
 * `PAUSED` is excluded by the status filter rather than by a second check:
 * pausing is what the eligibility recheck does when an advertiser stops
 * clearing the bar, and a paused campaign that kept being delivered would make
 * that pause decorative.
 */
async function liveCampaigns(now: Date): Promise<SpotlightCampaign[]> {
  return prisma.spotlightCampaign.findMany({
    where: {
      status: "RUNNING",
      startsAt: { lte: now },
      // `endsAt` is pushed out on resume and extended by the sweep, so a row
      // whose window has passed is one the sweep has not reached yet — not a
      // campaign to keep delivering.
      endsAt: { gt: now },
    },
    orderBy: { startsAt: "asc" },
  });
}

/**
 * Whether this viewer may see this campaign at all.
 *
 * Deliberately one `count` against `audienceWhere` rather than a hand-rolled
 * comparison of ages and cities. The rule "money widens who sees you, it never
 * overrides what somebody said they wanted" lives in exactly one query, and a
 * second implementation of it here would be a second place for it to be wrong.
 */
async function viewerQualifies(campaign: SpotlightCampaign, advertiser: AdvertiserFacts, viewerUserId: string) {
  const exclusions = await resolveExclusions(advertiser);
  if (exclusions.includes(viewerUserId)) return false;

  const where = audienceWhere(
    advertiser,
    {
      cities: campaign.cities,
      minAge: campaign.minAge,
      maxAge: campaign.maxAge,
      targetGender: campaign.targetGender,
    },
    exclusions,
  );

  const match = await prisma.profile.count({ where: { AND: [where, { userId: viewerUserId }] } });
  return match > 0;
}

/** True when this member has already been shown a promoted card today, on any surface. */
async function viewerHitDailyCap(viewerUserId: string, now: Date): Promise<boolean> {
  const dayStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const shown = await prisma.spotlightDelivery.count({
    where: { viewerUserId, deliveredAt: { gte: dayStart } },
  });
  return shown >= MAX_PROMOTED_PER_VIEWER_PER_DAY;
}

/**
 * Which campaign gets the one slot, when several qualify.
 *
 * The furthest behind wins, measured as delivered-over-promised, and a tie
 * goes to whichever window closes first. Not first-come or highest-paid:
 * either of those lets one campaign monopolise the single daily slot while a
 * second one bought on the same day quietly runs out of days. Sorting by
 * shortfall is what makes the inventory share itself out without anybody
 * scheduling it.
 */
function pickContender(contenders: Contender[]): Contender | null {
  if (contenders.length === 0) return null;
  return [...contenders].sort((a, b) => {
    const progressA = a.campaign.deliveredReach / Math.max(1, a.campaign.promisedReach);
    const progressB = b.campaign.deliveredReach / Math.max(1, b.campaign.promisedReach);
    if (progressA !== progressB) return progressA - progressB;
    return (a.campaign.endsAt?.getTime() ?? Infinity) - (b.campaign.endsAt?.getTime() ?? Infinity);
  })[0];
}

export interface PlacementResult {
  campaignId: string;
  /** The advertiser's profile — the card to insert. */
  profileId: string;
  /** Where in the deck it goes. Never below `MIN_ORGANIC_CARDS_BEFORE_PROMOTED`. */
  rank: number;
}

/**
 * Pick at most one promoted card for a reel that is being generated.
 *
 * `organicProfileIds` is the deck as scored so far. It matters for two
 * reasons: a profile already in the deck on merit must not be duplicated as a
 * paid card (the buyer would be paying for a slot they had already won), and
 * the deck's length decides whether there is room after the organic opening at
 * all.
 *
 * Returns null — the ordinary case, by a wide margin — when nothing qualifies.
 * A reel with no promoted card is the product working normally, not a failure
 * to fill inventory.
 */
export async function placeSpotlightCard(
  viewerUserId: string,
  organicProfileIds: string[],
  now = new Date(),
): Promise<PlacementResult | null> {
  // A deck too short to have an unsold opening gets no promoted card at all.
  // The rule is "never in the first three", and on a three-card reel that
  // leaves nowhere legal to put one.
  if (organicProfileIds.length < MIN_ORGANIC_CARDS_BEFORE_PROMOTED) return null;
  if (MAX_PROMOTED_PER_REEL < 1) return null;
  if (await viewerHitDailyCap(viewerUserId, now)) return null;

  const campaigns = await liveCampaigns(now);
  if (campaigns.length === 0) return null;

  const alreadySeen = new Set(
    (
      await prisma.spotlightDelivery.findMany({
        where: { viewerUserId, campaignId: { in: campaigns.map((c) => c.id) } },
        select: { campaignId: true },
      })
    ).map((d) => d.campaignId),
  );

  const organic = new Set(organicProfileIds);
  const contenders: Contender[] = [];

  for (const campaign of campaigns) {
    if (alreadySeen.has(campaign.id)) continue;
    if (campaign.ownerUserId === viewerUserId) continue;
    const remaining = campaign.promisedReach - campaign.deliveredReach;
    if (remaining <= 0) continue;

    const advertiser = await loadAdvertiserFacts(campaign.ownerUserId);
    // An advertiser whose profile lost its gender or date of birth cannot be
    // audience-matched at all. Skipping is right: the eligibility recheck is
    // what pauses such a campaign, and guessing here would deliver a card the
    // two-way filter was never applied to.
    if (!advertiser) continue;
    if (organic.has(advertiser.profileId)) continue;
    if (!(await viewerQualifies(campaign, advertiser, viewerUserId))) continue;

    contenders.push({ campaign, advertiser, remaining });
  }

  const winner = pickContender(contenders);
  if (!winner) return null;

  return {
    campaignId: winner.campaign.id,
    profileId: winner.advertiser.profileId,
    // Straight after the organic opening. Not random and not last: the rule is
    // a floor on how much unsold deck comes first, and burying the card at the
    // end of a twenty-card reel would sell a slot most people never scroll to.
    rank: MIN_ORGANIC_CARDS_BEFORE_PROMOTED,
  };
}

export interface DeliveryOutcome {
  /** Campaigns whose reach moved on this open. Usually 0 or 1. */
  recorded: number;
  /** Campaigns that hit their promised reach and were closed by this open. */
  completed: string[];
}

/**
 * Count the promoted cards in a reel the viewer just opened.
 *
 * Idempotent by construction, and that is the whole design: `SpotlightDelivery`
 * is unique on (campaign, viewer), so a member refreshing their reel eleven
 * times produces one row and one increment. `createMany({ skipDuplicates })`
 * reports how many rows it actually wrote, and only that number moves the
 * counter — which is why the second refresh adds nothing rather than adding
 * one more.
 *
 * The increment is `{ increment: n }` and not a recomputed total, so two
 * viewers opening at the same instant cannot read the same `deliveredReach`
 * and write it back twice.
 */
export async function recordReelDeliveries(
  viewerUserId: string,
  placements: { spotlightCampaignId: string | null }[],
  now = new Date(),
): Promise<DeliveryOutcome> {
  const campaignIds = [...new Set(placements.map((p) => p.spotlightCampaignId).filter((id): id is string => !!id))];
  if (campaignIds.length === 0) return { recorded: 0, completed: [] };

  const completed: string[] = [];
  let recorded = 0;

  for (const campaignId of campaignIds) {
    const written = await prisma.spotlightDelivery.createMany({
      data: [{ campaignId, viewerUserId, surface: "reel", deliveredAt: now }],
      skipDuplicates: true,
    });
    if (written.count === 0) continue;
    recorded += written.count;

    const updated = await prisma.spotlightCampaign.update({
      where: { id: campaignId },
      data: { deliveredReach: { increment: written.count } },
    });

    if (updated.status === "RUNNING" && updated.deliveredReach >= updated.promisedReach) {
      const closed = await prisma.spotlightCampaign.updateMany({
        where: { id: campaignId, status: "RUNNING" },
        data: { status: "COMPLETED", completedAt: now },
      });
      if (closed.count > 0) {
        completed.push(campaignId);
        await notifyCampaignFinished(updated.ownerUserId, updated.promisedReach);
      }
    }
  }

  return { recorded, completed };
}

async function notifyCampaignFinished(ownerUserId: string, reach: number): Promise<void> {
  await createNotice({
    userId: ownerUserId,
    kind: "SPOTLIGHT_UPDATE",
    title: "Spotlight poora hua",
    body: `Aapki profile ${reach} logon tak pahunch gayi. Jinhone interest bheja hai wo aapke inbox me hain.`,
    href: "/user/spotlight",
  }).catch((err) => {
    // A campaign that finished is a fact in the database. A notice that failed
    // to send must not roll that back into "still running".
    console.error("[spotlight] finish notice failed:", err instanceof Error ? err.message : String(err));
  });
}

/**
 * Rebuild `deliveredReach` from the delivery rows.
 *
 * The counter is a cache; these rows are the record. Exposed because a cache
 * that can never be checked against its source is a number nobody can defend
 * in a refund conversation — the sweep calls it before deciding what a
 * campaign is owed, so no refund is ever computed off a drifted counter.
 */
export async function recountDelivered(tx: Prisma.TransactionClient, campaignId: string): Promise<number> {
  const real = await tx.spotlightDelivery.count({ where: { campaignId } });
  await tx.spotlightCampaign.updateMany({
    where: { id: campaignId, deliveredReach: { not: real } },
    data: { deliveredReach: real },
  });
  return real;
}
